ARG CHECKMK_AGENT_VERSION=2.4.0-latest
ARG PROJECT_PYVERSION=1.0.0

FROM python:3.10-alpine AS base
RUN apk update && apk add --no-cache coreutils pciutils && \
    apk --no-cache upgrade --purge

FROM base AS builder
ARG PROJECT_PYVERSION
ARG CHECKMK_AGENT_VERSION
COPY ./requirements_build.txt /tmp
COPY dist/checkmk_kube_agent-"${PROJECT_PYVERSION}".tar.gz /tmp/

COPY ./check_mk_agent.openwrt /install/bin/check_mk_agent.openwrt
COPY ./mk_inventory.linux /install/bin/mk_inventory.linux
COPY ./lnx_container_host_if.linux /install/bin/lnx_container_host_if.linux
COPY docker/kubernetes-collector/wrapper.sh /install/bin/check_mk_agent

RUN pip3 install --no-cache-dir -r /tmp/requirements_build.txt && \
    pip3 install --no-cache-dir --prefix=/install /tmp/checkmk_kube_agent-"$PROJECT_PYVERSION".tar.gz && \
    sed -i "s/VERSION_CMK/${CHECKMK_AGENT_VERSION}/" /install/bin/check_mk_agent && \
    sed -i "s/VERSION_AGENT/${PROJECT_PYVERSION}/" /install/bin/check_mk_agent && \
    chmod +x /install/bin/check_mk_agent && \
    rm -rf /tmp/* && \
    rm -rf /var/cache/apk/*

FROM base AS release
ARG CHECKMK_AGENT_VERSION
ARG GIT_HASH
ENV CHECKMK_AGENT_VERSION="${CHECKMK_AGENT_VERSION}"
COPY --from=builder /install /usr/local
RUN addgroup appgroup -g 10001 && \
    adduser -HD appuser -G appgroup -u 10001
RUN echo "${GIT_HASH}" > GIT_HASH.txt
RUN pip3 install --no-cache-dir \
        "pip>=26.0" \
        "setuptools>=79.0.1" \
        "wheel>=0.46.2" && \
    pip3 install --no-cache-dir --force-reinstall \
        "starlette>=0.47.2" \
        "urllib3>=2.6.3" \
        "jaraco.context>=6.1.0" && \
    find /usr/local/lib -path "*/setuptools/_vendor/jaraco.context*" -exec rm -rf {} + && \
    find /usr/local/lib -path "*/setuptools/_vendor/wheel*" -exec rm -rf {} +

FROM release
USER appuser
